node {
   def commit_id
   //We have two options, 1: to SCM from Pipeline Script from SCM, 2: Use our own declartive Github repo
   stage('checkout'){
      git branch: 'main',
          url: 'https://github.com/850mayr/ci-cd.git'
   }
   stage('step a') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       dir("basics"){
        sh 'npm install --only=dev'
        sh 'npm test'
       }
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'docker_hub') {
       def app = docker.build("850mayr/jenkins_course:${commit_id}", '.').push()
     }
   }
   stage('docker run') {
     sh label: '',
     script: '''
      docker run --rm -tid --name docker_test -p 3000 850mayr/jenkins_course:latest
      docker kill docker_test
      '''
    }
}

